services:
  app:
    image: "${CI_REGISTRY_IMAGE}/app:${CI_COMMIT_REF_NAME}"
#    ports:
#      - "8000:8000"
    volumes:
      - dev-static-data:/vol/web

  db:
    volumes:
      - dev-db-data:/var/lib/postgresql/data

  celery:
    image: "${CI_REGISTRY_IMAGE}/app:${CI_COMMIT_REF_NAME}"
    volumes:
      - dev-static-data:/vol/web

  flower:
    image: "${CI_REGISTRY_IMAGE}/flower:${CI_COMMIT_REF_NAME}"
    ports:
      - "5554:5555"

  proxy:
    image: "${CI_REGISTRY_IMAGE}/proxy:${CI_COMMIT_REF_NAME}"
    build:
      context: ./proxy
    depends_on:
      - app
    ports:
      - 8000:8000
    env_file:
      - ./envs/.env.proxy
    volumes:
      - dev-static-data:/vol/static

volumes:
  dev-static-data:
  dev-db-data:
