services:
  app:
    image: app:latest  # Local image
    ports:
      - "8000:8000"
    command: >
      sh -c "sh ./scripts/wait_for_rabbitmq.sh &&
             sh ./scripts/wait_for_redis.sh &&
             cd core &&
             python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./core:/app/core
      - ./scripts:/app/scripts
      - fc-dev-static-data:/vol/web

  db:
    volumes:
      - fc-dev-db-data:/var/lib/postgresql/data

  redis:
    ports:
      - "6379:6379"

  rabbitmq:
    ports:
      - "5672:5672"   # main service port (AMQP)
      - "15672:15672" # management console port

  celery:
    image: app:latest  # Local image
    volumes:
      - ./core:/app/core
      - fc-dev-static-data:/vol/web

  flower:
    ports:
      - "5555:5555"

volumes:
  fc-dev-static-data:
  fc-dev-db-data:
