services:
  app:
    build:
      context: .
    command: >
      sh -c "sh ./scripts/wait_for_rabbitmq.sh &&
             sh ./scripts/wait_for_redis.sh &&
             cd core &&
             python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./envs/.env
    depends_on:
      - db
      - redis
      - rabbitmq
      - celery

  db:
    image: postgres:16-alpine
    env_file:
      - ./envs/.env.db

  redis:
    image: redis:7.2.0-alpine

  rabbitmq:
    image: rabbitmq:3.11-management
    env_file:
      - ./envs/.env.rabbitmq

  celery:
    build:
      context: .
    command: >
      sh -c "sh ./scripts/wait_for_rabbitmq.sh &&
             sh ./scripts/wait_for_redis.sh &&
             cd core &&
             python manage.py wait_for_db &&
             celery --app=core worker --loglevel=INFO --queues=tasks -B"
    env_file:
      - ./envs/.env
    depends_on:
      - redis
      - rabbitmq

  flower:
    build:
      context: .
      dockerfile: ./flower/Dockerfile
    env_file:
      - ./envs/.env.flower
    depends_on:
      - celery
      - rabbitmq
      - redis
