services:
  app:
    image: "${CI_REGISTRY_IMAGE}/app:${CI_COMMIT_REF_NAME}"
    command: >
      sh -c "sh ./scripts/wait_for_rabbitmq.sh &&
             sh ./scripts/wait_for_redis.sh &&
             cd core &&
             python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             uwsgi --socket :8000 --workers 4 --master --enable-threads --module core.wsgi"
    volumes:
      - dev-static-data:/vol/web

  db:
    volumes:
      - dev-db-data:/var/lib/postgresql/data

  celery:
    image: "${CI_REGISTRY_IMAGE}/app:${CI_COMMIT_REF_NAME}"
    volumes:
      - dev-static-data:/vol/web

  flower:
    image: "${CI_REGISTRY_IMAGE}/flower:${CI_COMMIT_REF_NAME}"
    ports:
      - "5554:5555"

  proxy:
    image: "${CI_REGISTRY_IMAGE}/proxy:${CI_COMMIT_REF_NAME}"
    build:
      context: ./proxy
    depends_on:
      - app
    ports:
      - 8000:8000
    env_file:
      - ./envs/.env.proxy
    volumes:
      - dev-static-data:/vol/static

volumes:
  dev-static-data:
  dev-db-data:
