services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./core:/core
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./envs/.env

    depends_on:
      - db


  db:
    image: postgres:16-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - ./envs/.env.db


volumes:
  dev-db-data:
  dev-static-data:
